import {Project} from "./project";

export const PROJECTS: Project[] = [
	{ id: 11,
		name : 'Project 1',
		region : 'Еврейская автономная область',
		initiators : [],
		industry : 'Недра (Графитовая промышленность)',
		investmentsSummValue : 4.7,
		investmentsSummCurrency : 'млрд руб.',
		paybackSummValue : 4.8,
		paybackSummCurrency : 'лет',
		normalSummValue : 4.8,
		normalSummCurrency : 'лет',
		periodSummValue : 4.8,
		periodSummCurrency : 'лет',
		description: []
	},
	{ id: 12,
		name : 'Project 2',
		region : 'Еврейская автономная область',
		initiators : [],
		industry : 'Недра (Графитовая промышленность)',
		investmentsSummValue : 4.7,
		investmentsSummCurrency : 'млрд руб.',
		paybackSummValue : 4.8,
		paybackSummCurrency : 'лет',
		normalSummValue : 4.8,
		normalSummCurrency : 'лет',
		periodSummValue : 4.8,
		periodSummCurrency : 'лет',
		description: []
	},
	{ id: 13,
		name : 'Project 3',
		region : 'Еврейская автономная область',
		initiators : [],
		industry : 'Недра (Графитовая промышленность)',
		investmentsSummValue : 4.7,
		investmentsSummCurrency : 'млрд руб.',
		paybackSummValue : 4.8,
		paybackSummCurrency : 'лет',
		normalSummValue : 4.8,
		normalSummCurrency : 'лет',
		periodSummValue : 4.8,
		periodSummCurrency : 'лет',
		description: []
	},
	{ id: 14,
		name : 'Project 4',
		region : 'Еврейская автономная область',
		initiators : [],
		industry : 'Недра (Графитовая промышленность)',
		investmentsSummValue : 4.7,
		investmentsSummCurrency : 'млрд руб.',
		paybackSummValue : 4.8,
		paybackSummCurrency : 'лет',
		normalSummValue : 4.8,
		normalSummCurrency : 'лет',
		periodSummValue : 4.8,
		periodSummCurrency : 'лет',
		description: []
	},
	{ id: 15,
		name : 'Project 5',
		region : 'Еврейская автономная область',
		initiators : [],
		industry : 'Недра (Графитовая промышленность)',
		investmentsSummValue : 4.7,
		investmentsSummCurrency : 'млрд руб.',
		paybackSummValue : 4.8,
		paybackSummCurrency : 'лет',
		normalSummValue : 4.8,
		normalSummCurrency : 'лет',
		periodSummValue : 4.8,
		periodSummCurrency : 'лет',
		description: []
	}
];